### ISSUE TITLE
Compilte error: register in #import incorrect.

### ISSUE THREAD

**Issue by StasanTelnov** [myTrackerSDK/mytracker-ios#1]
Hello.
After install myTracker via cocoapods, I have a compile error in `MRMyTracker.h` file in imports directive 
```
#import <myTrackerSDK/MRMyTrackerParams.h>
#import <myTrackerSDK/MRMyTrackerConfig.h>
#import <myTrackerSDK/MRMyTrackerAttribution.h>
```
that file `myTrackerSDK/MRMyTrackerParams.h` not found
https://prnt.sc/t1z2ui

But, if I change folder register to CamelCase style, all work normal:
```
#import <MyTrackerSDK/MRMyTrackerParams.h>
#import <MyTrackerSDK/MRMyTrackerConfig.h>
#import <MyTrackerSDK/MRMyTrackerAttribution.h>
```

In others files imports is correct (`MyTrackerSDK.h` for example)
```
#import <MyTrackerSDK/MRMyTracker.h>
#import <MyTrackerSDK/MRMyTrackerConfig.h>
#import <MyTrackerSDK/MRMyTrackerParams.h>
#import <MyTrackerSDK/MRMyTrackerAttribution.h>
```

Please, fix folder name register in `MRMyTracker.h` in next releases.

**Comment by altk** [comment]
Fixed in 2.0.6
