### ISSUE TITLE
-com.apple.CoreData.ConcurrencyDebug 2 issue

### ISSUE THREAD

**Issue by mrbesford** [myTrackerSDK/mytracker-ios#2]
Hi, after update framework, we get app crash with  -com.apple.CoreData.ConcurrencyDebug, how we can fix it?
Stack trace:
<img width="725" alt="Screenshot 2020-10-09 at 19 01 27" src="https://user-images.githubusercontent.com/24810439/95605722-044a8f00-0a62-11eb-8519-896e90ca1d87.png">

**Comment by altk** [comment]
It seems like a duplicate of
https://developer.apple.com/forums/thread/662602
