### ISSUE TITLE
VALID_ARCHS is no longer supported by Xcode since 12 release

### ISSUE THREAD

**Issue by DmitryArbuzov** [myTrackerSDK/mytracker-ios#4]
Guys, could you remove VALID_ARCHS from podspec? 
These params leads to warnings during compilation.

**Comment by altk** [comment]
Hi!
Could you provide warning messages or full build log?

**Comment by DmitryArbuzov** [comment]
<img width="763" alt="xcode myTargetSDK" src="https://user-images.githubusercontent.com/8289095/139098700-5d1b1f40-74ea-451d-905d-a32181dd4369.png">

Xcode 13

**Comment by altk** [comment]
> <img alt="xcode myTargetSDK" width="763" src="https://user-images.githubusercontent.com/8289095/139098700-5d1b1f40-74ea-451d-905d-a32181dd4369.png">
> 
> Xcode 13

Which version of pods do you use?

Additionally, could you provide sample app with issue?

**Comment by DmitryArbuzov** [comment]
COCOAPODS: 1.11.0

**Comment by altk** [comment]
> COCOAPODS: 1.11.0

I have the similar environment: xCode 13, cocoapods 1.11.2; and I can't reproduce the issue in our demo app.
Which steps lead to the problem? Could you reproduce it in the demo? If could, can you provide step by step guide?

**Comment by altk** [comment]
No response, so closing the issue.
